-- Seed data
INSERT INTO groups (group_id, group_name, group_desc, group_status, group_createtime, group_updatetime)
VALUES (1, '超级管理员', '不允许删除', 0, 0, 1575903468);

-- Default admin: admin / Admin123!  (salt=abcd, password sha1)
-- password hash computed at runtime bootstrap if missing; seed placeholder
INSERT INTO admin (admin_id, admin_account, admin_password, admin_salt, admin_name, admin_group, admin_ipreg, admin_status, admin_createtime, admin_updatetime)
VALUES (1, 'admin', 'BOOTSTRAP', 'abcd', '管理员', 1, '127.0.0.1', 0, strftime('%s','now'), strftime('%s','now'));

INSERT INTO source_category (source_category_id, name, image, sort, status, is_sys, is_update, is_type, create_time, update_time) VALUES
(1, '短剧', '', 999, 0, 1, 1, 0, strftime('%s','now'), strftime('%s','now')),
(2, '电影', '', 998, 0, 1, 1, 0, strftime('%s','now'), strftime('%s','now')),
(3, '电视剧', '', 997, 0, 1, 1, 0, strftime('%s','now'), strftime('%s','now')),
(4, '动漫', '', 996, 0, 1, 1, 0, strftime('%s','now'), strftime('%s','now')),
(5, '综艺', '', 995, 0, 1, 1, 0, strftime('%s','now'), strftime('%s','now'));

INSERT INTO node (node_id, node_title, node_desc, node_module, node_controller, node_action, node_pid, node_order, node_show, node_icon, node_status, node_createtime, node_updatetime) VALUES
(1, '概况', '', 'qfadmin', 'index', 'index', 0, 999, 1, 'house', 0, 0, 0),
(2, '运营人员', '', 'qfadmin', '', '', 3, 0, 1, 'user', 0, 0, 0),
(3, '系统', '', 'qfadmin', '', '', 0, 0, 1, 'board', 0, 0, 0),
(4, '配置', '', 'qfadmin', '', '', 0, 0, 1, 'setting', 0, 0, 0),
(100, '管理员列表', '', 'qfadmin', 'admin', 'index', 2, 0, 1, 'user', 0, 0, 0),
(101, '用户组管理', '', 'qfadmin', 'group', 'index', 2, 0, 1, '', 0, 0, 0),
(102, '参数配置', '', 'qfadmin', 'conf', 'index', 4, 5, 1, 'setup', 0, 0, 0),
(104, '菜单管理', '', 'qfadmin', 'node', 'index', 4, 6, 1, 'menu', 0, 0, 0),
(105, '附件管理', '', 'qfadmin', 'attach', 'index', 4, 4, 1, 'attach', 0, 0, 0),
(106, '清理数据', '', 'qfadmin', 'system', 'clean', 0, 0, 0, '', 0, 0, 0),
(107, '基础设置', '', 'qfadmin', 'conf', 'base', 3, 5, 1, 'ops', 0, 0, 0),
(108, '资源', '', 'qfadmin', '', '', 0, 1, 1, 'files', 0, 0, 0),
(109, '资源管理', '', 'qfadmin', 'source', 'index', 108, 10, 1, 'folder', 0, 0, 0),
(112, '账号管理', '', 'qfadmin', 'source', 'deposit', 108, 1, 1, 'deposit', 0, 0, 0),
(113, '资源日志', '', 'qfadmin', 'source', 'log', 108, 8, 1, 'log', 0, 0, 0),
(114, '用户需求', '', 'qfadmin', 'source', 'feedback', 108, 1, 1, 'edit', 0, 0, 0),
(118, '分类管理', '', 'qfadmin', 'source', 'category', 108, 9, 1, 'cat', 0, 0, 0),
(119, '接口配置', '', 'qfadmin', 'source', 'apilist', 108, 1, 1, 'link', 0, 0, 0);

INSERT INTO conf (conf_key, conf_value, conf_title, conf_desc, conf_spec, conf_type, conf_status, conf_sort, conf_system, conf_createtime, conf_updatetime) VALUES
('app_name', 'PanSearch', '网站名称', '', 0, 0, 1, 99, 1, strftime('%s','now'), strftime('%s','now')),
('app_title', 'PanSearch - 网盘资源搜索', 'SEO标题', '', 0, 9, 1, 999, 1, strftime('%s','now'), strftime('%s','now')),
('app_keywords', '网盘,搜索,资源', 'SEO关键词', '', 1, 9, 1, 998, 1, strftime('%s','now'), strftime('%s','now')),
('app_description', '网盘资源索引与搜索', 'SEO描述', '', 1, 9, 1, 996, 1, strftime('%s','now'), strftime('%s','now')),
('app_subname', '免费分享网盘资源，让您畅享资源无忧！', '网站宣传语', '', 0, 0, 1, 94, 1, strftime('%s','now'), strftime('%s','now')),
('logo', '', '网站LOGO', '', 4, 0, 1, 93, 1, strftime('%s','now'), strftime('%s','now')),
('app_icon', '', '网站icon', '', 4, 0, 1, 92, 1, strftime('%s','now'), strftime('%s','now')),
('app_name_hide', '0', '隐藏网站名称', '', 2, 0, 1, 98, 1, strftime('%s','now'), strftime('%s','now')),
('footer_dec', '声明：本站是网盘索引系统,所有内容均来自互联网所提供的公开引用资源。', '底部介绍', '', 1, 0, 1, 90, 1, strftime('%s','now'), strftime('%s','now')),
('footer_copyright', '© 2026 PanSearch', '底部版权', '', 1, 0, 1, 89, 1, strftime('%s','now'), strftime('%s','now')),
('search_type', '1', '搜索模式', '0精准 1模糊 2分词', 2, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('search_tips', '未找到，可换个关键词尝试哦~', '未搜索提示词', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('search_bg', '', '未搜索提示图', '', 4, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('is_quan', '1', '全网搜', '', 2, 1, 1, 1, 1, strftime('%s','now'), strftime('%s','now')),
('is_quan_type', '0', '全网搜模式', '0转存分享 1直链', 2, 1, 1, 1, 1, strftime('%s','now'), strftime('%s','now')),
('is_quan_zc', '0', '检测资源', '', 2, 1, 1, 1, 1, strftime('%s','now'), strftime('%s','now')),
('ban_keywords', '', '关键词屏蔽', '', 1, 1, 1, 1, 1, strftime('%s','now'), strftime('%s','now')),
('api_key', 'change-me', '接口api_key', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('upload_max_file', '4097152', '最大文件上传限制', '', 0, 2, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('upload_file_type', 'csv,xlsx', '允许文件上传类型', '', 0, 2, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('upload_max_image', '2097152', '最大图片上传限制', '', 0, 2, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('upload_image_type', 'jpg,png,gif,jpeg,bmp,webp', '允许上传图片类型', '', 0, 2, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('qcode', '', '群二维码', '', 4, 3, 1, 80, 1, strftime('%s','now'), strftime('%s','now')),
('home_bg', '', '大图背景', '', 4, 3, 1, 75, 1, strftime('%s','now'), strftime('%s','now')),
('home_background', '#fafafa', '背景颜色', '', 7, 3, 1, 74, 1, strftime('%s','now'), strftime('%s','now')),
('home_color', '#3e3e3e', '文字颜色', '', 7, 3, 1, 73, 1, strftime('%s','now'), strftime('%s','now')),
('home_theme', '#133ab3', '主题色', '', 7, 3, 1, 72, 1, strftime('%s','now'), strftime('%s','now')),
('other_background', '#ffffff', '其它元素背景', '', 7, 3, 1, 71, 1, strftime('%s','now'), strftime('%s','now')),
('home_css', '', '自定义CSS', '', 1, 3, 1, 70, 1, strftime('%s','now'), strftime('%s','now')),
('ranking_type', '0', '显示模式', '', 2, 3, 1, 79, 1, strftime('%s','now'), strftime('%s','now')),
('ranking_num', '10', '排行榜数量', '', 0, 3, 1, 78, 1, strftime('%s','now'), strftime('%s','now')),
('ranking_m_num', '6', '移动端限制数量', '', 0, 3, 1, 77, 1, strftime('%s','now'), strftime('%s','now')),
('home_new', '0', '最新列表', '', 2, 3, 1, 79, 1, strftime('%s','now'), strftime('%s','now')),
('home_new_img', '', '最新图标', '', 4, 3, 1, 79, 1, strftime('%s','now'), strftime('%s','now')),
('app_demand', '0', '提交需求', '', 2, 3, 1, 81, 1, strftime('%s','now'), strftime('%s','now')),
('app_links', '', '顶部其他外链', '', 1, 3, 1, 80, 1, strftime('%s','now'), strftime('%s','now')),
('pc_type', '0', 'PC端访问方式', '', 2, 3, 1, 90, 1, strftime('%s','now'), strftime('%s','now')),
('seo_statistics', '', '统计代码', '', 1, 9, 1, 995, 1, strftime('%s','now'), strftime('%s','now')),
('quark_cookie', '', '夸克Cookie', '', 0, 4, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('quark_banned', '失效,年会员,空间容量,微信,微信群,全网资源,影视资源,扫码,最新资源,公众号', '广告词', '', 1, 4, 1, 999, 1, strftime('%s','now'), strftime('%s','now')),
('quark_file', '', '夸克默认转存目录', '', 0, 4, 1, 98, 1, strftime('%s','now'), strftime('%s','now')),
('quark_file_time', '', '夸克临时资源目录', '', 0, 4, 1, 97, 1, strftime('%s','now'), strftime('%s','now')),
('baidu_cookie', '', '百度Cookie', '', 0, 4, 1, 89, 1, strftime('%s','now'), strftime('%s','now')),
('baidu_file', '', '百度默认转存目录', '', 0, 4, 1, 88, 1, strftime('%s','now'), strftime('%s','now')),
('baidu_file_time', '', '百度临时资源目录', '', 0, 4, 1, 87, 1, strftime('%s','now'), strftime('%s','now')),
('Authorization', '', '阿里Authorization', '', 0, 4, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('ali_file', 'root', '阿里默认转存目录', '', 0, 4, 1, 78, 1, strftime('%s','now'), strftime('%s','now')),
('ali_file_time', 'root', '阿里临时资源目录', '', 0, 4, 1, 77, 1, strftime('%s','now'), strftime('%s','now')),
('uc_cookie', '', 'UcCookie', '', 0, 4, 1, 69, 1, strftime('%s','now'), strftime('%s','now')),
('uc_file', '', 'UC默认转存目录', '', 0, 4, 1, 68, 1, strftime('%s','now'), strftime('%s','now')),
('uc_file_time', '', 'UC临时资源目录', '', 0, 4, 1, 67, 1, strftime('%s','now'), strftime('%s','now')),
('xunlei_cookie', '', '迅雷Cookie', '', 0, 4, 1, 59, 1, strftime('%s','now'), strftime('%s','now')),
('xunlei_file', '', '迅雷默认转存目录', '', 0, 4, 1, 58, 1, strftime('%s','now'), strftime('%s','now')),
('xunlei_file_time', '', '迅雷临时资源目录', '', 0, 4, 1, 57, 1, strftime('%s','now'), strftime('%s','now')),
('mp4_online', '0', '在线观看资源', '', 2, 4, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('transfer_feed_url', '', '日更聚合源地址', 'QuarkPlugin 外部 feed 根 URL', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('wechat_app_id', '', '微信AppId', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('wechat_secret', '', '微信Secret', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('wechat_token', '', '微信Token', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('wechat_aes_key', '', '微信AESKey', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('chatbot_app_id', '', 'Chatbot AppId', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('chatbot_token', '', 'Chatbot Token', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('chatbot_aes_key', '', 'Chatbot AESKey', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now')),
('chatbot_name', 'PanSearch', 'Chatbot 回复名称', '', 0, 1, 1, 0, 1, strftime('%s','now'), strftime('%s','now'));
